"""Execution Agent for running generated PySpark code."""

import logging
import uuid
from typing import Optional, Dict, Any

from src.config import get_settings
from src.types import Agent, AgentType, AgentStatus, AgentInput, AgentOutput
from src.agents.coding_agent.schemas import GeneratedCode
from src.execution.spark_executor import LocalSparkExecutor
from src.lineage.extractor import LineageExtractor
from src.lineage.emitter import LineageEmitter

logger = logging.getLogger(__name__)


class ExecutionAgentInput:
    """Input for Execution Agent."""

    def __init__(self, generated_code: GeneratedCode):
        self.generated_code = generated_code


class ExecutionAgentOutput:
    """Output from Execution Agent."""

    def __init__(
        self,
        execution_status: str,
        duration_seconds: float,
        stdout: str,
        stderr: str,
        execution_result: Optional[Dict[str, Any]] = None,
        error_message: Optional[str] = None,
        lineage: Optional[Dict[str, Any]] = None,
    ):
        self.execution_status = execution_status
        self.duration_seconds = duration_seconds
        self.stdout = stdout
        self.stderr = stderr
        self.execution_result = execution_result
        self.error_message = error_message
        self.lineage = lineage or {}

    def model_dump(self):
        """Convert to dictionary."""
        return {
            "execution_status": self.execution_status,
            "duration_seconds": self.duration_seconds,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "execution_result": self.execution_result,
            "error_message": self.error_message,
            "lineage": self.lineage,
        }


class ExecutionAgent(Agent):
    """Execution Agent: Runs generated PySpark code.

    This agent takes code generated by the Coding Agent and executes it,
    capturing outputs, logs, and execution metrics.
    """

    def __init__(self, use_local_executor: bool = True):
        """Initialize the Execution Agent.

        Args:
            use_local_executor: If True, use LocalSparkExecutor (no Spark needed).
                              If False, use full SparkExecutor with spark-submit.
        """
        super().__init__(AgentType.TASK)  # Using TASK type as placeholder
        self.settings = get_settings()
        self.use_local_executor = use_local_executor

        if use_local_executor:
            self.executor = LocalSparkExecutor()
        else:
            from src.execution.spark_executor import SparkExecutor
            self.executor = SparkExecutor()

        logger.info(
            f"ExecutionAgent initialized with "
            f"{'local' if use_local_executor else 'spark-submit'} executor"
        )

    async def execute(self, agent_input: AgentInput) -> AgentOutput:
        """Execute the generated code and extract lineage.

        Args:
            agent_input: Should contain generated_code.

        Returns:
            AgentOutput with execution results and lineage information.
        """
        execution_id = str(uuid.uuid4())
        lineage_data = {}
        
        try:
            # Parse input
            if isinstance(agent_input, dict):
                agent_input_dict = agent_input
            else:
                agent_input_dict = agent_input.model_dump() if hasattr(agent_input, "model_dump") else agent_input

            if "generated_code" not in agent_input_dict:
                return self._error_output("Missing 'generated_code' in agent input")

            generated_code_data = agent_input_dict["generated_code"]

            # Extract code to execute
            if isinstance(generated_code_data, dict):
                code_to_execute = generated_code_data.get("code", "")
            else:
                code_to_execute = generated_code_data.code if hasattr(generated_code_data, "code") else ""

            if not code_to_execute:
                return self._error_output("No code to execute found in generated_code")

            logger.info("Starting code execution with lineage tracking...")
            
            # Extract lineage from code before execution
            lineage_extractor = LineageExtractor(
                execution_id=execution_id,
                pipeline_name="etl_pipeline"
            )
            pipeline_lineage = lineage_extractor.extract(code_to_execute)
            lineage_data = pipeline_lineage.to_dict()
            
            logger.info(f"Extracted lineage: {len(pipeline_lineage.sources)} sources, {len(pipeline_lineage.targets)} targets")
            
            # Emit START event
            lineage_emitter = LineageEmitter(execution_id=execution_id, backend="local")
            lineage_emitter.emit_start(
                pipeline_name="etl_pipeline",
                inputs=pipeline_lineage.sources
            )

            # Execute the code
            execution_result = self.executor.execute_code(
                code=code_to_execute,
                job_name="etl_pipeline_execution",
                use_local_mode=self.use_local_executor,
            )

            logger.info(
                f"Execution completed with status: {execution_result['status']} "
                f"in {execution_result['duration_seconds']:.2f}s"
            )
            
            # Emit COMPLETE event with results
            lineage_emitter.emit_complete(
                pipeline_name="etl_pipeline",
                inputs=pipeline_lineage.sources,
                outputs=pipeline_lineage.targets,
                status=execution_result['status'],
            )
            
            # Emit full lineage
            lineage_emitter.emit_lineage(pipeline_lineage)

            # Create output with lineage information
            execution_output = ExecutionAgentOutput(
                execution_status=execution_result["status"],
                duration_seconds=execution_result["duration_seconds"],
                stdout=execution_result["stdout"],
                stderr=execution_result["stderr"],
                execution_result=execution_result.get("execution_result"),
                error_message=execution_result.get("error"),
                lineage=lineage_data,
            )

            # Calculate quality score based on execution success
            quality_score = 1.0 if execution_result["status"] == "success" else 0.0

            return AgentOutput(
                agent_type=self.agent_type,
                status=AgentStatus.SUCCESS if execution_result["status"] == "success" else AgentStatus.FAILURE,
                data={
                    **execution_output.model_dump(),
                    "quality_score": quality_score,
                },
            )

        except Exception as e:
            logger.error(f"Execution Agent failed: {str(e)}", exc_info=True)
            return self._error_output(f"Execution Agent failed: {str(e)}")

    def validate_input(self, agent_input: AgentInput) -> bool:
        """Validate input contains generated code.

        Args:
            agent_input: Input to validate.

        Returns:
            True if valid, False otherwise.
        """
        try:
            if isinstance(agent_input, dict):
                agent_input_dict = agent_input
            else:
                agent_input_dict = agent_input.model_dump() if hasattr(agent_input, "model_dump") else agent_input

            return "generated_code" in agent_input_dict

        except Exception:
            return False

    def _error_output(self, error_message: str) -> AgentOutput:
        """Create error output.

        Args:
            error_message: Error message.

        Returns:
            AgentOutput with error status.
        """
        return AgentOutput(
            agent_type=self.agent_type,
            status=AgentStatus.FAILURE,
            data={"error": error_message},
        )
